{"errorMessage":"Lambda runtime error. Result: {'errorMessage': \"a bytes-like object is required, not 'str'\", 'errorType': 'TypeError', 'stackTrace': ['  File \"/var/task/handler.py\", line 19, in handler\\n    raise e\\n', '  File \"/var/task/handler.py\", line 13, in handler\\n    if event and \"Records\" in event:\\n']}. Output:\nINIT: Using Lambda API Runtime target host: 'test-lambda.eu-central-1.localhost.localstack.cloud:4566'\nINIT: Starting daemons...\nINIT: Host 'test-lambda.eu-central-1.localhost.localstack.cloud' resolves to '172.29.0.3'\nls-daemon: Starting XRay server loop on UDP port 2000\nls-daemon: Starting DNS server loop on UDP port 53\n-----\n[INFO]\t2021-06-22T11:29:41.611Z\t405f9738\t## ENVIRONMENT VARIABLES environ({'HOSTNAME': '3243a4a34c45', 'LOCALSTACK_DEBUG': '1', 'LOCALSTACK_HOSTNAME': '172.29.0.3', 'LAMBDA_TASK_ROOT': '/var/task', 'LD_LIBRARY_PATH': '/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib:/opt/lib:/opt/python/lib/python3.8/site-packages:/opt/python/lib/python3.7/site-packages:/opt/python/lib/python3.6/site-packages:/opt/python/lib/python2.7/site-packages', 'AWS_LAMBDA_LOG_GROUP_NAME': '/aws/lambda/test-lambda', 'AWS_LAMBDA_RUNTIME_API': 'test-lambda.eu-central-1.localhost.localstack.cloud:4566', 'AWS_LAMBDA_LOG_STREAM_NAME': 'test', '_LAMBDA_RUNTIME': 'None', 'AWS_EXECUTION_ENV': 'AWS_Lambda_python3.8', 'AWS_XRAY_DAEMON_ADDRESS': '127.0.0.1:2000', 'PATH': '/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin:/opt/bin', 'PWD': '/var/task', 'AWS_SECRET_ACCESS_KEY': 'test', 'LAMBDA_RUNTIME_DIR': '/var/runtime', 'LANG': 'en_US.UTF-8', 'NODE_PATH': ':/opt/nodejs/node_modules:/opt/nodejs/node8/node_modules:/opt/nodejs/node10/node_modules:/opt/nodejs/node12/node_modules:/var/runtime/node_modules:/var/task:/var/task/node_modules', 'TZ': ':/etc/localtime', 'AWS_ACCESS_KEY_ID': 'test', 'SHLVL': '1', 'HOME': '/root', 'LOCALSTACK_HOSTS_ENTRY': 'test-lambda.eu-central-1.localhost.localstack.cloud', '_AWS_XRAY_DAEMON_ADDRESS': '127.0.0.1', 'PYTHONPATH': ':/var/runtime:/opt:/opt/python:/opt/python/lib/python3.8/site-packages:/opt/python/lib/python3.7/site-packages:/opt/python/lib/python3.6/site-packages:/opt/python/lib/python2.7/site-packages', '_X_AMZN_TRACE_ID': 'f3fad07d', 'GEM_PATH': ':/opt/ruby/gems/2.5.0', 'CLASSPATH': ':/opt/java:/opt/java/lib', '_HANDLER': 'handler.handler', 'AWS_LAMBDA_FUNCTION_MEMORY_SIZE': '1536', 'RUBYLIB': ':/opt/ruby/lib'})\n[INFO]\t2021-06-22T11:29:41.611Z\t405f9738\t## EVENT b'{}'\n[INFO]\t2021-06-22T11:29:41.611Z\t405f9738\t## CONTEXT <__main__.LambdaContext object at 0x7f1509d9d790>\n[ERROR]\t2021-06-22T11:29:41.611Z\t405f9738\ta bytes-like object is required, not 'str'\n[ERROR] TypeError: a bytes-like object is required, not 'str'\rTraceback (most recent call last):\r\u00a0\u00a0File \"/var/task/handler.py\", line 19, in handler\r\u00a0\u00a0\u00a0\u00a0raise e\r\u00a0\u00a0File \"/var/task/handler.py\", line 13, in handler\r\u00a0\u00a0\u00a0\u00a0if event and \"Records\" in event:\n","errorType":"InvocationException","stackTrace":["  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 605, in run_lambda\n    version=version, asynchronous=asynchronous, callback=callback)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 183, in execute\n    return do_execute()\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 175, in do_execute\n    return _run(func_arn=func_arn)\n","  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 149, in wrapped\n    raise e\n","  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 145, in wrapped\n    result = func(*args, **kwargs)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 166, in _run\n    raise e\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 154, in _run\n    result = self._execute(func_arn, func_details, event, context, version)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 375, in _execute\n    result = self.run_lambda_executor(cmd, event=stdin, env_vars=environment, func_details=func_details)\n","  File \"/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/awslambda/lambda_extended.py\", line 357, in run_lambda_executor\n","  File \"/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/awslambda/lambda_extended.py\", line 246, in run_lambda_executor\n","  File \"/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/awslambda/lambda_extended.py\", line 276, in do_run_lambda_executor\n"]}
